pipeline {
agent any
stages {
stage('Repositiry') {
steps {
sh "git@github.com:maan98/jenkindemo2.git"
}
}
stage('Test') {
steps {
sh "mvn test -f jenkindemo2.gitt"
}
}
stage('Deploy') {
steps {
sh "mvn package -f jenkindemo2.git"
}
}
}
}
