pipeline {
agent any
stages {
stage('Repositiry') {
steps {
sh "https://github.com/Mahesh8143/MyFirstProject.git"
}
}
stage('Test') {
steps {
sh "mvn test -f MyFirstProject.gitt"
}
}
stage('Deploy') {
steps {
sh "mvn package -f MyFirstProject.git"
}
